### PR TITLE
testing for end sem pull req

### PR DESCRIPTION
**Pull request by Tushar-Arora14**

### CODE REVIEW

**Comment by abhishek30221** [comment]
hey abhishek, 
you need to first go to your sections folder.
after that create a folder with suitable name convention.
after that put all work and files inside that created directory
and lastly make a pull request by closing current pull request.

**Comment by Tushar-Arora14** [comment]
This is for web practical exam right?
I was testing the pull request if anything wrong tell me

**Comment by abhishek30221** [comment]
No Tushar, 
This is not for practicals. 
you have not put your files under section folder and specified directory.

**Comment by Tushar-Arora14** [comment]
Now i did kindly check and revert.

**Pull request closed without merging**
